name: Deploy Backend to Azure App Service

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Adjust this to match your backend Node.js version requirement

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Write Certificate to File
        run: echo "${{ secrets.CERT }}" > dist/DigiCertGlobalRootCA.crt.pem

      - name: Copy ecosystem.config.js to dist
        run: cp ecosystem.config.js dist/

      - name: Copy package.json to dist
        run: cp package.json dist/

      - name: Copy package-lock.json to dist
        run: cp package-lock.json dist/

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "eor-backend"  # Replace with your Azure App Service name for the backend
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: dist/  # Replace with the directory containing your compiled backend code

      - name: Install PM2 Globally on Azure
        run: npm install pm2 -g

      - name: Install Production Dependencies on Azure
        run: npm install

      - name: Start Backend with PM2
        run: pm2 start main.js --no-daemon
